@startuml dominio

class Charger {
    + String id
    + int numberOfPoints
    + String usageCost
    + boolean isFavorito
    + double costeTotal
    + maxPower() : double
    + costeTotalCarga(double capacidadBateria, double porcentajeBateriaActual) : double
    - obtenerMenorPrecio(String cadena) : double
    + hashCode() : int
    + equals(Object obj) : boolean
}

class Operator {
    + int id
    + String title
    + String website
    + String comments
}

class Address {
    + String title
    + String town
    + String province
    + String latitude
    + String longitude
    + String addressLine1
    + String addressLine2
}

class Favourite {
    + List<String> listaFavoritos
    + addCharger(String id) : String
}

class Connection {
    + String id
    + double powerKW
    + int quantity
}

class ConnectionType {
    + String id
    + String formalName
    + String title
}

class StatusType {
    + String id
    + boolean isOperational
}

Charger -down-> "1" Address : address
Charger -down-> "1" Operator : operator
Charger -down-> "*" Connection : connections

Connection -down-> "1" ConnectionType : connectionType
Connection -down-> "1" StatusType : connectionStatus

@enduml
