@startuml dominio

class Charger {
    + String id
    + int numberOfPoints
    + String usageCost
    + boolean isFavorito
    + maxPower() : double
}

class Operator {
    + int id
    + String title
    + String website
    + String comments
}

class Address {
    + String title
    + String town
    + String province
    + String latitude
    + String longitude
    + String addressLine1
    + String addressLine2
}

class Favourite {
    + addCharger(String id) : String
}

class Connection {
    + String id
    + double powerKW
    + int quantity
}

class ConnectionType {
    + String id
    + String formalName
}

class StatusType {
    + String id
    + boolean isOperational
}

Charger -down-> "1" Address : address
Charger -down-> "1" Operator : operator
Charger -down-> "*" Connection : connections

Favourite -right-> "*" Charger: listaFavoritos

Connection -down-> "1" ConnectionType : connectionType
Connection -down-> "1" StatusType : connectionStatus

@enduml